V_MAX = 10
MAX_WHEEL_SPEED = 2000
USE_VISUALIZATION = True
DRAW_LIDAR = True
DRAW_PARTICLES = True
DRAW_ROBOT = True

WIDTH = 1200
HEIGHT = 800

BEAM_LENGTH = 300
BEAM_COUNT = 3

AXLE_LENGTH = 10
WHEEL_RADIUS = 2.2
IMG_PATH = 'thymio_small.png'
GRID_SIZE = 20
NUM_PARTICLES = 200
NOISE_FACTOR = 0.01